meson: Fix pkg-config generation with internal dependencies
Prevents Meson error:

ERROR:  requires argument not a string, library with pkgconfig-generated
file or pkgconfig-dependency object, got <InternalDependency null: True>

Requires Meson 0.49.